# Generated by Django 3.1.3 on 2020-11-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('data_1', models.CharField(blank=True, max_length=200)),
                ('data_2', models.CharField(blank=True, max_length=200)),
                ('data_3', models.CharField(blank=True, max_length=200)),
                ('data_4', models.CharField(blank=True, max_length=200)),
                ('data_5', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
