# Generated by Django 3.1.3 on 2020-11-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
