# Generated by Django 3.1.3 on 2020-11-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='description',
            field=models.TextField(default=True, max_length=700),
            preserve_default=False,
        ),
    ]
